# -*- coding: utf-8 -*-
"""python-learning-journey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dL_HswvucqgnALdPPAWMN7TuXw-rqKzI

1. Tek mi Çift mi

Kullanıcı sayı girsin, tek mi çift mi yaz.
"""

while True:
  sayı=input("bir sayı giriniz(çıkmak için q):")

  if sayı=="q":
    print("program kapandı")
    break

  sayı=int(sayı)

  if sayı%2==0:
     print("çift sayıdır")
  else:
    print("tek sayıdır")

"""2. En Büyük Sayı Bulma

3 sayı alıp en büyüğünü bul.
"""

liste=[]
for i in range(3):
  sayı=int(input("bir sayı giriniz:"))
  liste.append(sayı) # Added this line to add the number to the list
max_liste=max(liste)
min_liste=min(liste)
print(f"en büyük sayı:{max_liste}")
print(f"en küçük sayı:{min_liste}")

"""3. Not Hesaplama

0-100 arası nota göre:

AA
BB
CC
FF

hesapla.
"""

notu=int(input("notunuzu giriniz:"))
if notu<0 and notu>100:
  print("geçersiz not girdiniz")
elif notu >= 90:
    print("AA")
elif notu >= 80:
    print("BB")
elif notu >= 70:
    print("CC")
elif notu >= 60:
    print("DC")
elif notu >= 50:
    print("DD")
else:
    print("FF")

"""4. Şifre Kontrolü

Doğru şifre girilene kadar tekrar sor.
"""

doğru_şifre=6295
while True:
  şifre=int(input("şifrenizi giriniz:"))
  if şifre==doğru_şifre:
    print("uygulamaya giriş yapıldı")
    break
  else:
    print("tekrar deneyiniz")

"""5. Faktöriyel Hesaplama

for ile yap bir de while ile yap.
"""

sayı=int(input("bir sayı giriniz:"))
faktöriyel=1
for i in range(1,sayı+1):
  faktöriyel*=i

print(f"{sayı} sayının faktöriyeli:{faktöriyel}")

sayı=int(input("bir sayı giriniz:"))
faktöriyel=1
i=1
while i<=sayı:
  faktöriyel*=i
  i+=1
print(f"{sayı}! = {faktöriyel}")

"""6. Asal Sayı Kontrolü

Fonksiyon kullanarak yap.
"""

def asal_mi(sayi):
    if sayi <= 1:
        return False

    for i in range(2, sayi):
        if sayi % i == 0:
            return False

    return True



print(asal_mi(7))
print(asal_mi(12))

"""7. Ortalama Hesaplama

Liste içindeki sayıların ortalamasını bul.
"""

def ortalama(liste):
  ortalama=sum(liste)/len(liste)
  print(f"girilen sayıların ortalaması={ortalama}")

ortalama([1,34,90,127,872])

"""8. Sayı Tahmin Oyunu

Random sayı üret, kullanıcı tahmin etsin.
"""

gerçek_sayı=65
while True:
  sayı=int(input("bir sayı giriniz:"))

  if sayı<0 and sayı>100:
    print("geçersiz bir sayı girdiniz")
    continue

  if sayı<gerçek_sayı:
    print("daha büyük sayı giriniz")
  elif sayı>gerçek_sayı:
    print("daha küçük sayı giriniz")
  else:
     print("tebrikler doğru sayıyı buldunuz")
     break

"""9. Kelime Sayacı

Cümlede kaç harf ve kaç kelime olduğunu bul.
"""

metin=input("bir metin giriniz:")
harf_sayısı=0
for harf in metin:
      if harf != " ":
        harf_sayısı+=1

kelime_sayısı=len(metin.split())

print(f"kelime sayısı:{kelime_sayısı}")
print(f"harf sayısı:{harf_sayısı}")

"""10. Fibonacci Serisi

İlk n elemanı yazdır.
"""

n=int(input("kaç terim yazdırmak istiyorsunuz:"))
a=0
b=1

for i in range(n):
  print(a)

  toplam=a+b
  a=b
  b=toplam